default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
      name: Blacken

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    - id: check-added-large-files
      args: [--maxkb=1024]
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-symlinks
    - id: end-of-file-fixer

  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.0'
    hooks:
    -   id: flake8
